# Generated by Django 5.2.9 on 2025-12-04 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="blogs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="blogview",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="views", to="analytics.blog"
            ),
        ),
        migrations.AddField(
            model_name="blogview",
            name="viewer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blogview",
            name="viewer_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_views",
                to="analytics.country",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to="analytics.country",
            ),
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(fields=["-viewed_at"], name="analytics_b_viewed__46a32c_idx"),
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(fields=["blog", "-viewed_at"], name="analytics_b_blog_id_09fc43_idx"),
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(fields=["viewer_user", "-viewed_at"], name="analytics_b_viewer__5c8a7d_idx"),
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(fields=["viewer_country", "-viewed_at"], name="analytics_b_viewer__94a35d_idx"),
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(fields=["viewer_user", "blog"], name="analytics_b_viewer__8c75bb_idx"),
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(fields=["viewer_country", "blog"], name="analytics_b_viewer__98479c_idx"),
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(
                fields=["viewer_user", "viewer_country", "-viewed_at"], name="analytics_b_viewer__fcfab7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["user", "-created_at"], name="analytics_b_user_id_57552f_idx"),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["country", "-created_at"], name="analytics_b_country_e3fd60_idx"),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["user", "country", "-created_at"], name="analytics_b_user_id_b85cf6_idx"),
        ),
    ]
