# Generated by Django 5.2.9 on 2025-12-05 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(fields=["viewer_country", "viewed_at", "blog"], name="analytics_b_viewer__c5f61c_idx"),
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(fields=["viewer_user", "viewed_at", "blog"], name="analytics_b_viewer__1c351d_idx"),
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(fields=["blog", "viewed_at", "viewer_user"], name="analytics_b_blog_id_6eca25_idx"),
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(fields=["blog", "viewed_at", "viewer_country"], name="analytics_b_blog_id_36bdf3_idx"),
        ),
    ]
